name: aggfly-dev
channels:
  - conda-forge
dependencies:
  - python=3.11.6
  - dill=0.3.7
  - geopandas=0.14.1
  - numba=0.58.1
  - numpy=1.26.0
  - pandas=2.1.3
  - pygeos=0.14
  - PyYAML=6.0.1
  - rasterio=1.3.8
  - rioxarray=0.15.0
  - setuptools=68.2.2
  - Shapely=2.0.1
  - xarray=2023.10.1
  - zarr=2.16.1
  - ipykernel=6.26.0
  - notebook=7.0.6
  - dask=2023.11.0
  - dask-geopandas=0.3.1
  - pytest=8.0.0
  - netCDF4=1.6.4