name: aggfly-dev-2
channels:
  - conda-forge
dependencies:
  - dill=0.3.6
  - geopandas=0.12.2
  - numba=0.55.2
  - numpy=1.22.4
  - pandas=1.4.3
  - pygeos=0.14
  - PyYAML=6.0.1
  - rasterio=1.3.6
  - rioxarray=0.11.1
  - setuptools=61.2.0
  - Shapely=2.0.1
  - xarray=0.20.1
  - zarr=2.11.3
